const main = async () => {
  // write your code here
}

main()
  .then(() => {
    console.log("done")
  })
  .catch((err: unknown) => {
    console.error(err)
    process.exit(1)
  })
